### ISSUE TITLE
I can only list content

### ISSUE THREAD

**Issue by adocampo** [maxint/kuaipan#1]
Hello, 

Firts of all, thank you for your work, seems promising!!
I've just installed the requirements and executed the main.py script and I can see the content on my drive! Download and upload files... more or less... 
I had in mind to mount via fuse the drive on my raspberry pi, and then share the content via samba/dlna... it did not work, but anyway on my intel i7 it does ;)
The problem is it damn slow...and downloads seems that are always corrupted.

I have a 200/200Mb fiber connection and I can upload and download with pretty acceptable speeds via kuaipan4k (linux desktop app), but with your work... I'm afraid to say its almost impossible... I did the test with some pictures, and after a while, the copied file has reduced size on the downloaded, on kuaipan drive the picture' size was 1,5MB and the copied on my hard disk, 115KB... obviously, when open the image, it was completely corrupted.

I tried also to open with mplayer and vlc a video directly from the fuse mountpoint, also without success...  :(

I do not have my programmer skill developed, so I cannot help you coding at the moment (I'm starting learning python), but perhaps you could take a look on another project using fusepy, Megafuse, that works pretty nice: https://github.com/matteoserva/MegaFuse

Regards, 
Angel

**Comment by maxint** [comment]
Hi, Angel

Thanks for your detailed report. It happened when FUSE reads file in multiple-thread mode. I had fix the bug today. Currently the file data is cached in memory, and it's not efficient. So the script may occupy more and more memory when more operations. Maybe I would improve the cache system someday.

Regards,
maxint

**Comment by adocampo** [comment]
Hi maxint, 
Good job! Now I can download files from kuaipan, it's damn slow, but it works. I tried to play with vlc a video stored on it, but I'm not so lucky :P
I keep an eye on your project!
Regards, 
Angel

**Comment by maxint** [comment]
Hi malevolent,

Thanks for your detailed issue report!

Recently, I read document of FUSE file system again, and found the reason why large files (e.g. video) do not works. I updated the scripts and add some other features. It would worth to update and try it if you are still use it.

Regards,
maxint
